{% set version = "3.1.7" %}

package:
  name: pyopengl
  version: {{ version }}

source:
  fn: PyOpenGL-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyOpenGL/PyOpenGL-{{ version }}.tar.gz
  sha256: eef31a3888e6984fd4d8e6c9961b184c9813ca82604d37fe3da80eb000a76c86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python >=2.7

  run:
    - python >=2.7

test:
  imports:
    - OpenGL.GL

about:
  home: http://pyopengl.sourceforge.net
  license: LicenseRef-pyopengl
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  doc_url: http://pyopengl.sourceforge.net/documentation/index.html
  doc_source_url: https://sourceforge.net/projects/pyopengl/
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
