{% set version = "3.1.1a1" %}

package:
  name: pyopengl
  version: {{ version }}

source:
  fn: PyOpenGL-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/P/PyOpenGL/PyOpenGL-{{ version }}.tar.gz
  sha256: c96d909b359abe3271b746bacf7e6ba52935141e2406a8f90231e4e44dfa4075

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - setuptools
    - python

  run:
    - python

test:
  imports:
    - OpenGL.GL

about:
  home: http://pyopengl.sourceforge.net
  license: BSD-like
  license_file: license.txt
  summary: Standard OpenGL bindings for Python
  doc_url: http://pyopengl.sourceforge.net/documentation/index.html
  doc_source_url: https://sourceforge.net/projects/pyopengl/
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - almarklein
    - mcfletch
    - tadeu
